### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by fergyfresh** [tmaier/docker-compose#11]
Hey, i don't know much about this, but I'm trying to use your container to do the following.
```
docker-compose up
pip install -r requirements.txt
python -m unittest
```
I know this isn't much to go off of, but i noticed the latest docker build on dockerhub uses python2.7 and was wondering if you could point me in the right direction of making this python3.6 compatible provided you think its possible.

**Comment by tmaier** [comment]
Related PR #12

**Comment by tmaier** [comment]
The use case you are describing works, but is unintended. See similar discussion on #3

**Comment by ollisal** [comment]
Python2 has reached end-of-life and docker-compose upstream is currently removing support for it: https://github.com/docker/compose/issues/6890

Current docker-compose also has some annoying bugs when used with Python2, e.g. https://github.com/docker/docker-py/issues/2425.

Thus, changing to python3 sooner rather than later would be a good idea for docker-compose usage alone.

**Comment by ollisal** [comment]
My fork of another similar Docker image, tiangolo/docker-with-compose, at https://github.com/JaksoSoftware/docker-with-compose uses Python 3.8. It's available as `python3` inside the container.

Published as [ollisal/docker-with-compose](https://hub.docker.com/repository/docker/ollisal/docker-with-compose)

**Comment by tmaier** [comment]
@ollisal can you open a pull request?

**Comment by tmaier** [comment]
@ollisal your link does not work. Can you open a pull request?
